#Database: PostgresSQL

development:
        adapter: postgresql
        encoding: utf8
        database: static_pages
        pool: 5
        username:
        password:
        min_messages: WARNING

test: &TEST
        adapter: postgresql
        encoding: utf8
        database: static_pages_test
        pool: 5
        username:
        password:

production:
                adapter: postgresql
                encoding: utf8
                database: static_pages
                pool: 5
                username:
                password:


cucumber:
        <<: *TEST
